version: "3.7"

services:
  app:
    image: zwilson/pymail
    build: .
    env_file: secrets/pymail/.env
    ports:
      - 8025:8025
    environment:
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=465
    configs:
      - source: setup.cfg
        target: /usr/src
    volumes:
      - .:/usr/src
      - ./config/pymail/pymail.cfg:/usr/src/pymail.cfg
    command: pipenv run python -m pytest

configs:
  setup.cfg:
    file: ./setup.cfg
